# Site settings
title: "Chaoxi Xu"
description: "Chaoxi's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "徐朝喜"
resume_name_en:                    "Chaoxi Xu"
resume_title:                   "简介"
resume_title_en:                   "About me"

# used for the contact button in _layouts/resume.html
#resume_contact_email:           "xuchaoxi@ict.ac.cn"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "用技术让世界更可信"
display_header_contact_info:    "false"

resume_header_intro: "<p>我是一名算法工程师，目前就职于中科院计算所数字内容合成与伪造检测实验室，主要负责虚假新闻检测和AIGC检测的研究与应用，参与开发了多个伪造检测算法并且落地应用，包括多模态虚假新闻检测、多领域虚假新闻检测、基于事实信息的虚假新闻检测等和伪造音频检测、预训练大模型生成文本检测，作为核心成员参与的数字内容虚假伪造检测系统和设备获得<a class=\"link\" href=\"http://www.cac.gov.cn/2022-11/09/c_1669622017501892.htm\" target=\"_blank\">2022年世界互联网领先科技成果</a>。 </p>
<p>在此之前，我于2017年和2020年分别在中国人民大学获得了本科和硕士学位。在研究生期间，我师从<a class=\"link\" href=\"http://lixirong.net\" target=\"_blank\">李锡荣教授</a>，并在<a class=\"link\" href=\"https://ruc-aimc-lab.github.io\" target=\"_blank\">人工智能与媒体计算实验室</a>从事跨模态视频检索、AI医学影像分析领域的相关研究。在相关领域主要国际期刊和会议如TPAMI、TMM、TKDE、ACMMM、CVPR、MICCAI等发表论文10余篇，并且分别在2018年TRECVID Ad-hoc视频检索、视频文本检索比赛和Hulu基于内容的视频相关性预测比赛获得第一名，在2019年获得国家奖学金。</p>
<p>Email: xuchaoxi AT ict.ac.cn</p>
"

resume_header_intro_en: "<p>Currently, I am an algorithm engineer working in the Media Synthesis & Forensics Lab of the Institute of Computing Technology, Chinese Academy of Sciences. I focus on the research and application of fake news detection and AIGC detection. I have participated in the development of multiple media forgery detection algorithms, including multi-modal fake news detection, multi-domain fake news detection, factual information based fake news detection, fake audio detection, and text detection generated by pre-trained large models, etc. The media forgery detection system and equipment participated as a core member won the <a class=\"link\" href=\"http://www.cac.gov.cn/2022-11/09/c_1669622017501892.htm\" target=\"_blank\">2022 World Leading Internet Scientific and Technological Achievements award</a>.</p>
<p>Before that, I received B.S. and M.S. degrees at Renmin University of China in 2017 and 2020, respectively. During my postgraduate study, I was advised by <a class=\"link\" href=\"http://lixirong.net\" target=\"_blank\">Prof. Xirong Li</a>, and has been working in the fields of cross-modal video retrieval and AI medical image analysis in the <a class=\"link\" href=\"https://ruc-aimc-lab.github.io\" target=\"_blank\">AI & Media Computing Lab(AIMC)</a>. Published more than 10 papers in major international journals and conferences in related fields, such as TPAMI, TMM, TKDE, ACMMM, CVPR, MICCAI, etc., and won the 2018 TRECVID Ad-hoc Video Search(AVS) task, Video-to-Text(VTT) task and Hulu Content-Based Video Relevance Prediction Challenge, National Scholarship in 2019.</p>
<p>Email: xuchaoxi AT ict.ac.cn</p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "false"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
resume_section_awards:          true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/xuchaoxi"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  resume_googlescholar_url:           "https://scholar.google.com/citations?user=0z9o2CIAAAAJ"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
